//this file is generated by program automatically,don't modify it!
#include <cnet/http/NotFound.h>
#include <string>
#include <sstream>
#include <map>
#include <vector>
#include <set>
using namespace cnet;
std::string NotFound::genText()
{
	std::stringstream NotFound_tmp_stream;
	NotFound_tmp_stream << "<html>\n";
	NotFound_tmp_stream << "<head><title>404 Not Found</title></head>\n";
	NotFound_tmp_stream << "<body bgcolor=\"white\">\n";
	NotFound_tmp_stream << "<center><h1>404 Not Found</h1></center>\n";
	NotFound_tmp_stream << "</body>\n";
	NotFound_tmp_stream << "</html>\n";
	NotFound_tmp_stream << "<!-- a padding to disable MSIE and Chrome friendly error page -->\n";
	NotFound_tmp_stream << "<!-- a padding to disable MSIE and Chrome friendly error page -->\n";
	NotFound_tmp_stream << "<!-- a padding to disable MSIE and Chrome friendly error page -->\n";
	NotFound_tmp_stream << "<!-- a padding to disable MSIE and Chrome friendly error page -->\n";
	NotFound_tmp_stream << "<!-- a padding to disable MSIE and Chrome friendly error page -->\n";
	NotFound_tmp_stream << "<!-- a padding to disable MSIE and Chrome friendly error page -->\n";
	return NotFound_tmp_stream.str();
}
